mochidev/swift-webpush

Sources/WebPush/Helpers/DataProtocol+Base64URLCoding.swift
Sources/WebPush/VAPID/VAPIDKey.swift
Sources/WebPush/WebPushManager.swift
Tests/WebPushTests/Base64URLCodingTests.swift

Added proper Base64 URL coding support.

Base64 URL Coding

---

Sources/WebPush/Helpers/DataProtocol+Base64URLCoding.swift
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/VAPID/VAPIDKey.swift
Sources/WebPush/VAPID/VAPIDToken.swift
Tests/WebPushTests/VAPIDTokenTests.swift

Added working VAPID authorization header generation.

VAPID Authentication Header

---

Sources/WebPush/Helpers/URL+Origin.swift
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/VAPID/VAPIDToken.swift
Sources/WebPush/WebPushManager.swift

Added Authorization header caching per spec.

Authorization Header Caching

---

Sources/WebPush/Subscriber.swift
Sources/WebPush/VAPID/VAPIDKey.swift

Added a model for subscribers that can be decoded from the browser.

Subscribers Model

---

Package.swift
Sources/WebPush/Helpers/FixedWidthInteger+BigEndienBytes.swift
Sources/WebPush/Helpers/StringProtocol+UTF8Bytes.swift
Sources/WebPush/Subscriber.swift
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/WebPushManager.swift

Added a first pass at sending messages.

Sending Push Messages

---

Package.swift
README.md
Sources/WebPush/Helpers/HTTPClientProtocol.swift
Sources/WebPush/Helpers/PrintLogHandler.swift
Sources/WebPush/Subscriber.swift
Sources/WebPush/WebPushManager.swift
Sources/WebPushTesting/VAPIDConfiguration+Testing.swift
Sources/WebPushTesting/WebPushManager+Testing.swift
Tests/WebPushTests/MockHTTPClient.swift

Added full mocking capabilities to the push manager.

Mocked Types

---

Sources/WebPush/WebPushManager.swift

Without the timeout the request expires immediately and results in the `HTTPClientError.deadlineExceeded`.
I'm not sure why the async methods of AsyncHTTPClient don't allow a `nil` deadline like other methods (to use the overall client default).
This patch makes it work, but maybe there should be a more general way to configure the timeout.

Add a timeout

---

README.md
Sources/WebPush/Helpers/DataProtocol+Base64URLCoding.swift
Sources/WebPush/VAPID/VAPIDKey.swift
Tests/WebPushTests/Base64URLCodingTests.swift
Tests/WebPushTests/VAPIDConfigurationTests.swift
Tests/WebPushTests/VAPIDTokenTests.swift
vapid-key-generator/Sources/VAPIDKeyGenerator.swift

Added more test coverage on the configuration side of things, increasing coverage to 50%. Also added a helper for decoding keys directly from base64 data.

More Tests

---

Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/WebPushManager.swift
Sources/WebPushTesting/WebPushManager+Testing.swift
Tests/WebPushTests/VAPIDConfigurationTests.swift
Tests/WebPushTests/WebPushTests.swift

Added a new Expiration type to represent when messages are expired during delivery. Also added more focus to VAPID Configuration Durations, which are now conceptually separate.

Expirations

---

Sources/WebPush/WebPushManager.swift

Updated HTTP call to use a deadline set to the distant future to use the HTTP configuration's timeouts directly. This matches what APNSwift is doing, and observing the code in AsyncHTTPClient, seems to be what the NIO-based execution methods do as well when it is set to nil (though in that case, they skip adding a deadline task to cancel the request).

HTTP Deadlines

---

README.md
Sources/WebPush/Errors/HTTPError.swift
Sources/WebPush/Helpers/URL+Origin.swift
Sources/WebPush/Subscriber.swift
Sources/WebPush/VAPID/VAPID.swift
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/VAPID/VAPIDToken.swift

Improved the style of RFC docs by adding a space, and listing them all in the readme.

RFC Doc Style

---

Sources/WebPush/Subscriber.swift
Sources/WebPush/VAPID/VAPID.swift
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/VAPID/VAPIDKey.swift

Swapped the definitions for VAPID and its fully qualified name so the fully qualified one is the type alias.

VAPID Definition Refactor

---

Package.swift
README.md
Tests/WebPushTests/VAPIDConfiguration+Testing.swift
Tests/WebPushTests/VAPIDConfigurationTests.swift
Tests/WebPushTests/WebPushTests.swift

Added a sanity test that sends a string push message without verifying it.

Sanity Test

---

README.md
Sources/WebPush/VAPID/VAPIDKey.swift
Sources/WebPush/VAPID/VAPIDToken.swift

Added more docs to internal types.

VAPID Token Documentation

---

.spi.yml
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/WebPushManager.swift
Sources/WebPushTesting/VAPIDConfiguration+Testing.swift
Sources/WebPushTesting/VAPIDKey+Testing.swift
Sources/WebPushTesting/WebPushManager+Testing.swift
Tests/WebPushTests/VAPIDConfigurationTests.swift
Tests/WebPushTests/WebPushManagerTests.swift

Added more documentation and test coverage, bringing it up to 84%.

More Test Coverage

---

Sources/WebPushTesting/VAPIDConfiguration+Testing.swift
Sources/WebPushTesting/WebPushManager+Testing.swift
Tests/WebPushTests/WebPushManagerTests.swift

Renamed `VAPID.Configuration.mocked` to `VAPID.Configuration.mockedConfiguration`.

Mocked Configuration Rename

---

README.md
Sources/WebPush/WebPushManager.swift
Tests/WebPushTests/WebPushManagerTests.swift

Fixed an issue where a manager would not be properly shut down unless it was cancelled.

Automatic Shutdown

---

Sources/WebPush/WebPushManager.swift
Sources/WebPushTesting/WebPushManager+Testing.swift
Tests/WebPushTests/WebPushManagerTests.swift

- Updated the main logger logic to use a fallback logger rather than a child logger, based on feedback from [slack](https://swift-open-source.slack.com/archives/CN4BCMN8Z/p1734512151763979)
- Renamed `WebPushManager`'s logger to `backgroundActivityLogger` to match `AsyncHTTPClient`'s use of a similar logger.
- Added `logger`s to the send methods.
- Added much more comprehensive logging metadata.
- Fixed the logging level of service logs to one appropriate for libraries.
- Fixed some missing backticks on documentation.

Better Logging

---

Sources/WebPush/Errors/MessageTooLargeError.swift
Sources/WebPush/WebPushManager.swift
Sources/WebPushTesting/Subscriber+Testing.swift
Sources/WebPushTesting/WebPushManager+Testing.swift
Tests/WebPushTests/WebPushManagerTests.swift

Added a new error for push service rejections due to large messages (`MessageTooLargeError`), and added a variety of new mock methods to the Testing library for `Subscriber`s.

MessageTooLarge, more Mocks

---

Sources/WebPush/Errors/BadSubscriberError.swift
Sources/WebPush/Errors/Base64URLDecodingError.swift
Sources/WebPush/Errors/HTTPError.swift
Sources/WebPush/Errors/MessageTooLargeError.swift
Sources/WebPush/Errors/UserAgentKeyMaterialError.swift
Sources/WebPush/Errors/VAPIDConfigurationError.swift
Sources/WebPush/WebPushManager.swift
Tests/WebPushTests/BytesTests.swift
Tests/WebPushTests/ErrorTests.swift
Tests/WebPushTests/SubscriberTests.swift
Tests/WebPushTests/URLOriginTests.swift
Tests/WebPushTests/VAPIDKeyTests.swift
Tests/WebPushTests/WebPushManagerTests.swift

Since exit tests are not yet supported by Swift Testing, this now covers pretty much all the important code in the project.

Full Test Coverage

---

Package.swift
README.md
Sources/WebPush/Errors/BadSubscriberError.swift
Sources/WebPush/Errors/Base64URLDecodingError.swift
Sources/WebPush/Errors/HTTPError.swift
Sources/WebPush/Errors/MessageTooLargeError.swift
Sources/WebPush/Errors/UserAgentKeyMaterialError.swift
Sources/WebPush/Errors/VAPIDConfigurationError.swift
Sources/WebPush/Helpers/DataProtocol+Base64URLCoding.swift
Sources/WebPush/Helpers/HTTPClientProtocol.swift
Sources/WebPush/Helpers/PrintLogHandler.swift
Sources/WebPush/VAPID/VAPID.swift
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/VAPID/VAPIDKey.swift
Sources/WebPush/VAPID/VAPIDToken.swift
Sources/WebPush/WebPushManager.swift

Added more commendation coverage, including a usage guide in the read me.

Documentation

---

Sources/WebPush/WebPushManager.swift
Sources/WebPushTesting/WebPushManager+Testing.swift
Tests/WebPushTests/Helpers/MockHTTPClient.swift
Tests/WebPushTests/WebPushManagerTests.swift

Adds support for automatic retries, and configuring network options during initialization.

Retries and Network Configuration

---

README.md
Sources/WebPush/Errors/PushServiceError.swift
Sources/WebPush/Helpers/URL+Origin.swift
Sources/WebPush/Subscriber.swift
Sources/WebPush/Topic.swift
Sources/WebPush/VAPID/VAPID.swift
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/VAPID/VAPIDKey.swift
Sources/WebPush/VAPID/VAPIDToken.swift
Sources/WebPush/WebPushManager.swift

Fleshed out the remaining read me documentation.

Documentation Completeness

---

Sources/WebPush/Errors/BadSubscriberError.swift
Sources/WebPush/Errors/Base64URLDecodingError.swift
Sources/WebPush/Errors/MessageTooLargeError.swift
Sources/WebPush/Errors/PushServiceError.swift
Sources/WebPush/Errors/UserAgentKeyMaterialError.swift
Sources/WebPush/Errors/VAPIDConfigurationError.swift
Sources/WebPush/Helpers/DataProtocol+Base64URLCoding.swift
Sources/WebPush/Helpers/PrintLogHandler.swift
Sources/WebPush/Helpers/URL+Origin.swift
Sources/WebPush/Subscriber.swift
Sources/WebPush/Topic.swift
Sources/WebPush/VAPID/VAPID.swift
Sources/WebPush/VAPID/VAPIDConfiguration.swift
Sources/WebPush/VAPID/VAPIDKey.swift
Sources/WebPush/VAPID/VAPIDToken.swift
Sources/WebPush/WebPushManager.swift
Sources/WebPushTesting/Subscriber+Testing.swift
Sources/WebPushTesting/VAPIDConfiguration+Testing.swift
Tests/WebPushTests/Base64URLCodingTests.swift
Tests/WebPushTests/BytesTests.swift
Tests/WebPushTests/ErrorTests.swift
Tests/WebPushTests/Helpers/VAPIDConfiguration+Testing.swift
Tests/WebPushTests/SubscriberTests.swift
Tests/WebPushTests/TopicTests.swift
Tests/WebPushTests/URLOriginTests.swift
Tests/WebPushTests/VAPIDConfigurationTests.swift
Tests/WebPushTests/VAPIDKeyTests.swift
Tests/WebPushTests/VAPIDTokenTests.swift
Tests/WebPushTests/WebPushManagerTests.swift

Updated Foundation imports to lower binary size on linux.

FoundationEssentials

---

README.md

Fixed more typos in the README examples.

More README Fixes

---

README.md
Sources/WebPush/Push Message/Notification.swift
Sources/WebPush/Push Message/PushMessage.swift
Sources/WebPush/WebPushManager.swift

Added experimental declarative push notification support.

Experimental Declarative Push Notification Support

---

Sources/WebPush/WebPushManager.swift

Improved payload size slightly when sending JSON by omitting escaping slashes (`\/`), which are technically only needed within script tags.

JSON Packing Efficiency

---

Sources/WebPush/Push Message/Notification.swift
Sources/WebPush/WebPushManager.swift
Tests/WebPushTests/NeverTests.swift
Tests/WebPushTests/NotificationTests.swift
Tests/WebPushTests/WebPushManagerTests.swift

Added tests for declarative push notifications, and fixed an issue encoding notification actions and incorrect types on new send notification methods.

Declarative Push Notification Tests

---

README.md
Sources/WebPush/Push Message/Notification.swift
Sources/WebPush/Push Message/PushMessage.swift

Updated examples to use declarative push notifications.

Declarative Push Notification Examples

---

Sources/WebPush/Push Message/Notification.swift
Sources/WebPush/WebPushManager.swift
Sources/WebPushTesting/WebPushManager+Testing.swift
Tests/WebPushTests/MessageSizeTests.swift

Added methods to check the size of a message before sending it.

Check Size
